# Generated by Django 4.2.3 on 2023-08-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_paymentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll', models.CharField(max_length=255)),
                ('pandeduct', models.CharField(max_length=255)),
                ('tandeduct', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gstn', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
