# Generated by Django 4.2.3 on 2023-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0006_jobdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='clogo',
            field=models.FileField(null=True, upload_to='Files'),
        ),
        migrations.AddField(
            model_name='companies',
            name='max_crm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='max_emp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
