# Generated by Django 4.2.3 on 2023-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0007_companies_clogo_companies_max_crm_companies_max_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='regno',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
