# Generated by Django 4.2.3 on 2023-08-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0010_crm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crm',
            old_name='department',
            new_name='company',
        ),
    ]
