# Generated by Django 4.2.3 on 2023-08-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0013_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.country'),
        ),
    ]
