# Generated by Django 4.2.3 on 2023-08-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0014_alter_crm_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crm',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crm',
            name='updated_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
