# Generated by Django 4.2.3 on 2023-08-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0015_crm_created_at_crm_created_by_crm_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crm',
            old_name='credit_limt',
            new_name='credit_limit',
        ),
    ]
