# Generated by Django 4.2.3 on 2023-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0016_rename_credit_limt_crm_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
