# Generated by Django 4.2.4 on 2023-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0017_country_created_at_country_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('max_word', models.CharField(max_length=255, null=True)),
                ('min_word', models.CharField(max_length=255, null=True)),
                ('monthly_max_word', models.CharField(max_length=255, null=True)),
                ('monthly_min_word', models.CharField(max_length=255, null=True)),
                ('ppw', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('edited_by', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('month', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(max_length=255, null=True)),
            ],
        ),
    ]
