# Generated by Django 4.2.4 on 2023-08-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0018_emplevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentobank',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.companies'),
        ),
    ]
