# Generated by Django 4.2.4 on 2023-08-14 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0020_custlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmfmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='1', max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 5, 14, 40, 235490))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 5, 14, 40, 235500))),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teammaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=2555, null=True)),
                ('type', models.CharField(max_length=2555, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 5, 14, 40, 235116))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 5, 14, 40, 235132))),
                ('status', models.CharField(default='1', max_length=255)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('edited_by', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
