# Generated by Django 4.2.4 on 2023-08-14 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0021_cmfmaster_teammaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentobank',
            name='swift_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmfmaster',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 11, 32, 30, 475787)),
        ),
        migrations.AlterField(
            model_name='cmfmaster',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 11, 32, 30, 475797)),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 11, 32, 30, 475411)),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 11, 32, 30, 475427)),
        ),
    ]
