# Generated by Django 4.2.4 on 2023-08-16 11:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0022_paymentobank_swift_code_alter_cmfmaster_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketingstrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategymaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=255, null=True)),
                ('t1', models.CharField(max_length=255, null=True)),
                ('t2', models.CharField(max_length=255, null=True)),
                ('t3', models.CharField(max_length=255, null=True)),
                ('t4', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='1', max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termcondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.CharField(default='1', max_length=255)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cmfmaster',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmfmaster',
            name='updated_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='updated_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
