# Generated by Django 4.2.4 on 2023-08-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0023_marketingstrategy_strategymaster_termcondition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
