# Generated by Django 4.2.4 on 2023-08-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0024_designation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('edited_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('edited_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='teammaster',
            old_name='type',
            new_name='f_strategy',
        ),
        migrations.AddField(
            model_name='teammaster',
            name='m_strategy',
            field=models.CharField(max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='cmfmaster',
            name='created_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmfmaster',
            name='updated_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='custlevel',
            name='created_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='custlevel',
            name='updated_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='updated_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='updated_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='created_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='updated_at',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
