# Generated by Django 4.2.4 on 2023-08-21 05:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance', '0025_permission_role_rename_type_teammaster_f_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('department', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='1', max_length=255)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('edited_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teammaster',
            name='comp1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammaster',
            name='comp2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammaster',
            name='comp3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='f_strategy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='m_strategy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='team',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('pan', models.CharField(default='', max_length=20)),
                ('image', models.FileField(default='', upload_to='Files')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('doj', models.CharField(max_length=255, null=True)),
                ('dob', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('blood', models.CharField(max_length=20, null=True)),
                ('aadhar', models.CharField(max_length=20, null=True)),
                ('school', models.CharField(max_length=255, null=True)),
                ('degree', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('university', models.CharField(max_length=255, null=True)),
                ('marks', models.CharField(max_length=255, null=True)),
                ('ifsc', models.CharField(max_length=255, null=True)),
                ('accno', models.CharField(max_length=255, null=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('user_type', models.CharField(default='', max_length=255)),
                ('status', models.CharField(max_length=10, null=True)),
                ('salary', models.CharField(max_length=255, null=True)),
                ('init_level', models.CharField(default='', max_length=255)),
                ('curr_level', models.CharField(default='', max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.companies')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.designation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.location')),
                ('reported_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_to', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.role')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
