# Generated by Django 4.2.3 on 2023-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_dob_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
