# Generated by Django 4.2.3 on 2023-08-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
