# Generated by Django 4.2.3 on 2023-08-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_person_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=30)),
                ('stime', models.CharField(max_length=30)),
                ('etime', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='file',
            field=models.FileField(null=True, upload_to='Files'),
        ),
    ]
