# Generated by Django 4.2.3 on 2023-08-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_person_created_at_person_etime_person_shift_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
