# Generated by Django 4.2.3 on 2023-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_update_at_person_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentobank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_to_bank', models.CharField(max_length=255)),
                ('payroll', models.CharField(max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('account_no', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('pan', models.CharField(max_length=255, null=True)),
                ('ifsc', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(max_length=255)),
                ('updated_at', models.DateTimeField(max_length=255)),
            ],
        ),
    ]
