# Generated by Django 4.2.3 on 2023-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_paymentobank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=255)),
                ('payroll', models.CharField(max_length=255, null=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(max_length=255)),
                ('updated_at', models.DateTimeField(max_length=255)),
            ],
        ),
    ]
