# Generated by Django 4.2.3 on 2023-08-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_paymentobank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paymentmode',
        ),
    ]
