# Generated by Django 4.2.3 on 2023-08-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_companies_currencies_month_paymentmode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='Currencies',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
