# Generated by Django 4.2.3 on 2023-08-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_companies_delete_currencies_delete_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll', models.CharField(max_length=255)),
                ('pandeduct', models.CharField(max_length=255)),
                ('tandeduct', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gstn', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('updated_at', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Paymentmode',
        ),
    ]
