# Generated by Django 4.2.3 on 2023-08-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_currencies_delete_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
