# Generated by Django 4.2.3 on 2023-08-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paymentobank',
        ),
    ]
