# Generated by Django 4.2.3 on 2023-08-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_delete_paymentobank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
