# Generated by Django 4.2.3 on 2023-08-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Paymentmode',
        ),
        migrations.DeleteModel(
            name='Paymenttype',
        ),
    ]
